on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: |
        cd src
        dotnet build --configuration Release
    - name: Test
      run: |
        cd src/XmlToExpandoObjectConverter.Tests
        dotnet test --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Publish coverage report to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: src/XmlToExpandoObjectConverter.Tests/coverage.opencover.xml
        flags: unittests